# Default initial positions for model's ros2_control fake system

initial_positions:
  finger_joint: 0.0
  ur10e_elbow_joint: 1.570796327
  ur10e_shoulder_lift_joint: -2.443460953
  ur10e_shoulder_pan_joint: 2.443460953
  ur10e_wrist_1_joint: -1.570796327
  ur10e_wrist_2_joint: 1.570796327
  ur10e_wrist_3_joint: 0.0